---
title: "Rapport"
author: "ALIX Claire - ZEGHARI Saad"
institute : "INSA Toulouse"
date: "`r Sys.Date()`"
output: 
  pdf_document :
    toc : TRUE
    toc_depth : 2
    number_section : TRUE
header-includes:
   - \usepackage{dsfont}
   - \usepackage{color}
   - \newcommand{\1}{\mathds{1}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library(reticulate)
library(ggplot2)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(gridExtra)
```

On a 36 variables quantitavies (tous les tratements),
On a 3 variables qualitatives (Résultat/Génétique d'experience)


```{r,eval=F}
data<-read.table("data.txt",header=T, sep=";")
#head(data)
summary(data)
dim(data)
#nrow(data)
#ncol(data)
str(data)

Experience1 <- data[37]
levels(Experience1)

data$ExpT1 <- as.factor(data$ExpT1)
levels(data$ExpT1)
data$ExpT2 <- as.factor(data$ExpT2)
levels(data$ExpT2)
data$ExpT3 <- as.factor(data$ExpT3)
levels(data$ExpT3)


Eff1<-table(data$ExpT1)
df<-data.frame(Eff=c(Eff),Freq=c(Eff)/sum(Eff))
knitr::kable(t(df))

Eff2<-table(data$ExpT2)
df<-data.frame(Eff2=c(Eff2),Freq=c(Eff2)/sum(Eff2))
knitr::kable(t(df))

Eff3<-table(data$ExpT3)
df<-data.frame(Eff3=c(Eff3),Freq=c(Eff3)/sum(Eff3))
knitr::kable(t(df))

```
